## Inventorized objects

Script to inventorize the objects that the legacy Hive metastore manages or points to

In [3]:
catalog = "legacy_hms_dev"

inventory = []

schemas = [
    r.databaseName
    for r in spark.sql(f"SHOW DATABASES IN {catalog}").collect()
]

for schema in schemas:
    tables = spark.sql(f"SHOW TABLES IN {catalog}.{schema}").collect()

    for t in tables:
        table = t.tableName
        full_name = f"{catalog}.{schema}.{table}"

        try:
            desc = spark.sql(f"DESCRIBE EXTENDED {full_name}").collect()

            props = {
                r.col_name.strip(): str(r.data_type).strip()
                for r in desc
                if r.col_name
            }

            inventory.append({
                "schema": schema,
                "table": table,
                "type": props.get("Type"),
                "provider": props.get("Provider"),
                "location": props.get("Location")
            })

        except Exception as e:
            inventory.append({
                "schema": schema,
                "table": table,
                "type": "ERROR",
                "provider": None,
                "location": None
            })

df_inventory = spark.createDataFrame(inventory)

display(
    df_inventory.orderBy("schema", "type", "table")
)

DataFrame[location: string, provider: string, schema: string, table: string, type: string]

## Migration strategy

In [2]:
from pyspark.sql.functions import col, when

df_migration = (
    df_inventory
    .withColumn(
        "migration_strategy",
        when(
            (col("type") == "EXTERNAL") &
            col("location").startswith("abfss://"),
            "EXTERNAL_TO_UC"
        )
        .when(
            (col("type") == "MANAGED") &
            col("location").startswith("file:"),
            "COPY_TO_CLOUD_THEN_UC_MANAGED"
        )
        .otherwise("REVIEW")
    )
)

display(df_migration.orderBy("migration_strategy", "schema", "table"))

DataFrame[location: string, provider: string, schema: string, table: string, type: string, migration_strategy: string]